name: Deploy to slides repo

on: push

jobs:
  build-and-deploy:
    if: ${{ contains(github.event.head_commit.message, '[deploy]') }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Install and Build
      run: |
        npm install -g reveal-md
        cd slide/src
        make build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      with:
        branch: gh-pages
        folder: slide/src/site
